import type { Metadata } from "next";
import { getSessionUser } from "@/lib/auth/session";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { SeoLanding } from "@/components/SeoLanding";

export const metadata: Metadata = {
  title: 'Used Car Analysis — Full AI Report | VeltrixDrive',
  description: 'Full used-car analysis: deal score, market value, scam risk, known model issues, inspection checklist, and negotiation plan. Downloadable PDF included.',
  keywords: [
    "used car analysis",
    "used car report",
    "pre-purchase inspection",
    "car buyer guide",
    "used car checklist",
    "AI car report"
  ],
  openGraph: {
    title: "Used Car Analysis — Full AI Report in Seconds",
    description:
      "Full used-car analysis with deal score, market value, scam risk and an inspection checklist.",
    type: "website"
  },
  alternates: { canonical: "/used-car-analysis" }
};

export default async function UsedCarAnalysisPage() {
  const { user, credits } = await getSessionUser();
  const ctaHref = user ? "/dashboard" : "/login?next=/dashboard";

  return (
    <>
      <Header user={user} credits={credits} />
      <SeoLanding
        eyebrow="Used Car Analysis"
        h1="Used car analysis — the report a dealer won't give you"
        lede="Everything you need to make a confident decision about a used car, generated by an AI that behaves like a strict automotive analyst — not a chatbot."
        sections={[
          {
            title: "What a full used car analysis contains",
            body:
              "Deal score (1–10) with a one-line interpretation. A firm recommendation: buy, don't buy, or risky. A price evaluation comparing the asking price to the real market range for your year + mileage. A five-year depreciation chart with a twelve-month forecast. A reliability score calibrated to the exact make, model and generation. A year-one total cost of ownership estimate split by insurance, maintenance, tax and depreciation.\n\nThen the practical side: pros, cons, risks, known model-specific issues, a scam risk rating with concrete signals, a four-part inspection checklist (visual, mechanical, paperwork, red flags), and a negotiation plan with a suggested offer."
          },
          {
            title: "How it's different from a generic AI answer",
            body:
              "We lock down the things AI models get wrong. The listing price, mileage and year come from you — the model isn't allowed to invent them. Currency follows what you entered. The depreciation curve is non-linear and tuned to published retention data; it's not a straight downward line from a calculator.\n\nRed flags must be grounded in concrete facts. Phrases like 'inspect the car carefully' or 'check the engine' are automatically rejected as too generic. What you see instead is specific: '145,000 km on a BMW N47 diesel — request timing-chain replacement records before committing.'"
          },
          {
            title: "Built for EU, UK and US markets",
            body:
              "Pricing is regional. A six-year-old Toyota Corolla doesn't cost the same in Munich, Manchester and Miami. Our model infers the market from your currency and mileage unit, then uses the right price band and the right paperwork references — Carfax or AutoCheck in the US, MOT history in the UK, APK in the Netherlands, TÜV in Germany.\n\nWe serve both units: paste 78,500 miles or 145,000 km, the report adapts."
          },
          {
            title: "Who it's for",
            body:
              "Private buyers comparing three or four listings before committing. Sellers who want to price their own car correctly. People negotiating a trade-in value with a dealer. Buyers abroad who can't physically inspect before traveling. Anyone who has been burned by an emotional decision in the past and wants the data this time."
          }
        ]}
        ctaHeading="Get your full used car analysis now"
        ctaBody="Two free reports on signup. Downloadable PDF included."
        ctaLabel="Analyze a car"
        ctaHref={ctaHref}
        trustLine="We do not scrape listings. Provide key data for accurate results."
        relatedLinks={[
          { label: "Car value check", href: "/car-value-check" },
          { label: "Is this car worth it?", href: "/is-this-car-worth-it" },
          { label: "Car scam check", href: "/car-scam-check" }
        ]}
        faq={[
          { q: "What's included in a used car analysis?", a: "Deal score 1–10, buy / don't buy / risky verdict, market value range, depreciation forecast, reliability score, year-one cost of ownership breakdown, model-specific known issues, pros/cons/risks, scam risk assessment, four-part inspection checklist, and a negotiation plan with suggested offer. All in one report." },
          { q: 'How is the market value calculated?', a: 'We build the range independently from the asking price using make+model+generation+year+mileage and real retention data. If the listing sits within ±20% of the depreciation prediction, we trust the price as reasonable and build the range around it; otherwise we flag the discrepancy.' },
          { q: 'Can I download the report as a PDF?', a: "Yes. Every analysis has a Download button that produces a styled PDF with every section of the report, ready to share with a mechanic or family member. You're not charged a credit for the download — the analysis is already paid for." },
          { q: "How does it compare to a mechanic's inspection?", a: 'A mechanic checks the physical car; we check the paper deal. Use both. Our report tells you if the price and history pass initial scrutiny; the mechanic confirms the metal. Buyers who skip either step end up overpaying or buying salvage.' },
          { q: 'Do you scrape listing websites?', a: "No. You provide the key data (price, mileage, year) directly. This avoids anti-scraping issues and lets the tool work for any listing, including private sales that aren't on major platforms." }
        ]}
        pageUrl={`${(process.env.NEXT_PUBLIC_APP_URL || "https://veltrixdrive.com").replace(/\/$/, "")}/used-car-analysis`}
      />
      <Footer />
    </>
  );
}
