import { getSessionUser } from "@/lib/auth/session";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { LegalLayout } from "@/components/LegalLayout";

export const metadata = { title: "Terms of Service — VeltrixDrive" };

export default async function TermsPage() {
  const { user, credits } = await getSessionUser();

  return (
    <>
      <Header user={user} credits={credits} />
      <LegalLayout title="Terms of Service" lastUpdated="April 2026">
        <h2>1. Introduction</h2>
        <p>
          These Terms of Service (&quot;Terms&quot;) govern your access to and use of
          VeltrixDrive (&quot;the Service&quot;), an AI-powered car purchase decision
          platform operated by VeltrixDrive (KVK: 99933098). By creating an
          account or using the Service, you agree to be bound by these Terms.
        </p>

        <h2>2. The Service</h2>
        <p>
          VeltrixDrive analyzes car listings and descriptions provided by users
          and returns structured buying analyses, including estimated market
          values, deal scores, risks, and negotiation suggestions. These outputs
          are generated by artificial intelligence models and are provided for
          informational purposes only.
        </p>

        <h2>3. Eligibility and Accounts</h2>
        <ul>
          <li>You must be at least 18 years old to use the Service.</li>
          <li>
            You are responsible for maintaining the confidentiality of your
            credentials and for all activities under your account.
          </li>
          <li>
            You agree to provide accurate information when creating an account
            and to keep it up to date.
          </li>
        </ul>

        <h2>4. Credits and Usage</h2>
        <p>
          New users receive one (1) free analysis credit upon registration.
          Each completed analysis consumes one (1) credit. When your balance
          reaches zero, you must purchase additional credits or upgrade to
          continue using the analysis feature. Credits are non-refundable unless
          required by applicable law.
        </p>

        <h2>5. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service for any unlawful purpose.</li>
          <li>
            Attempt to reverse engineer, scrape, or circumvent the Service&apos;s
            security or credit system.
          </li>
          <li>
            Submit content that infringes third-party rights or contains
            malicious code.
          </li>
          <li>Resell or commercially redistribute analysis outputs without permission.</li>
        </ul>

        <h2>6. AI Disclaimer</h2>
        <p>
          VeltrixDrive provides AI-based informational estimates only and is not
          responsible for financial decisions made by users. The Service does
          not inspect vehicles physically, cannot verify seller claims, and may
          produce inaccurate or incomplete results. You remain fully responsible
          for any purchasing decision.
        </p>

        <h2>7. Intellectual Property</h2>
        <p>
          The Service, including its design, branding, code, and content,
          belongs to VeltrixDrive. You retain ownership of the inputs you
          submit; by using the Service you grant us a limited license to process
          those inputs to generate your analysis.
        </p>

        <h2>8. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, VeltrixDrive shall not be
          liable for any indirect, incidental, special, or consequential damages
          arising from your use of the Service, including but not limited to
          financial loss related to vehicle purchases.
        </p>

        <h2>9. Termination</h2>
        <p>
          We may suspend or terminate your account if you breach these Terms or
          misuse the Service. You may close your account at any time by
          contacting us.
        </p>

        <h2>10. Changes to These Terms</h2>
        <p>
          We may update these Terms from time to time. Significant changes will
          be communicated via email or in-app notice. Continued use after
          changes constitutes acceptance.
        </p>

        <h2>11. Governing Law</h2>
        <p>
          These Terms are governed by the laws of the Netherlands. Disputes
          shall be submitted to the competent courts in the Netherlands.
        </p>

        <h2>12. Contact</h2>
        <p>
          Questions about these Terms? Contact{" "}
          <a href="mailto:info@bedrijfsnaam.com">info@bedrijfsnaam.com</a>.
        </p>
      </LegalLayout>
      <Footer />
    </>
  );
}
